### ISSUE TITLE
争取在四月底前发布正式版本 v1.0.0

### ISSUE THREAD

**Issue by LKI** [zaihui/hutils#15]
争取四月底之前出一个正式的 1.0.0 版本吧，内容包括以下：

- [x] 兼容 3.5~3.8 的基础函数
  - [x] 所有函数都支持使用 `import hutils; hutils.some_func` 的方法 (#16)
- [x] 完备的单元测试
  - [x] 测一下 django 项目的函数 (#19)
  - [x] 测一下非 django 项目的函数 (#19)
- [x] 友好的文档
  - [x] 可以考虑直接用 README 替换 readthedocs (我们不需要那么重) (#21)
  - [x] 完备的 dev-env setup 以及 contribution 指引 (#21)
- [ ] 基建升级
  - [x] 使用 pipenv 替换 requirements (#14)
  - [ ] 使用 github actions 来发布包
  - [ ] 保持最新的库版本

**Comment by LKI** [comment]
@lxy1992 @ldsink @hulucc @Ehco1996 有兴趣的话欢迎来挑锅做哈

**Comment by hulucc** [comment]
![image](https://user-images.githubusercontent.com/4343900/78668436-45c07d00-790d-11ea-9d51-bcc235c30c1c.png)

**Comment by LKI** [comment]
得加油了…
隔壁 pipenv 都要发布了...
